"""Constants used across the matrimony bot — matched to the real Airtable schema."""

# ---------------- NAKSHATRA (27) ----------------
NAKSHATRA_LIST = [
    "Ashwini (అశ్విని)",
    "Bharani (భరణి)",
    "Krittika (కృతిక)",
    "Rohini (రోహిణి)",
    "Mrigashira (మృగశిర)",
    "Ardra (ఆర్ద్ర)",
    "Punarvasu (పునర్వసు)",
    "Pushya (పుష్యమి)",
    "Ashlesha (ఆశ్లేష)",
    "Magha (మఘ)",
    "Purva Phalguni (పూర్వ ఫల్గుణి)",
    "Uttara Phalguni (ఉత్తర ఫల్గుణి)",
    "Hasta (హస్త)",
    "Chitra (చిత్ర)",
    "Swati (స్వాతి)",
    "Vishakha (విశాఖ)",
    "Anuradha (అనూరాధ)",
    "Jyeshta (జ్యేష్ఠ)",
    "Moola (మూల)",
    "Purvashada (పూర్వాషాఢ)",
    "Uttarashada (ఉత్తరాషాఢ)",
    "Shravana (శ్రవణ)",
    "Dhanishta (ధనిష్ఠ)",
    "Shatabhisha (శతభిష)",
    "Purvabhadra (పూర్వభాద్ర)",
    "Uttarabhadra (ఉత్తరభాద్ర)",
    "Revati (రేవతి)",
]

# ---------------- RASHI (12) ----------------
RASHI_LIST = [
    "Mesha (మేషం)",
    "Vrishabha (వృషభం)",
    "Mithuna (మిథునం)",
    "Karka (కర్కాటకం)",
    "Simha (సింహం)",
    "Kanya (కన్యా)",
    "Tula (తుల)",
    "Vrischika (వృశ్చికం)",
    "Dhanu (ధనస్సు)",
    "Makara (మకరం)",
    "Kumbha (కుంభం)",
    "Meena (మీనం)",
]

# ---------------- SALARY BANDS ----------------
SALARY_BANDS = [
    "₹1–3 Lakhs",
    "₹3–6 Lakhs",
    "₹6–12 Lakhs",
    "₹12–25 Lakhs",
    "₹25–50 Lakhs",
    "₹50 Lakhs–₹1 Crore",
    "Above ₹1 Crore",
]

# ---------------- PROPERTY BANDS ----------------
PROPERTY_BANDS = [
    "₹1 Lakh – ₹10 Lakhs",
    "₹10 Lakhs – ₹50 Lakhs",
    "₹50 Lakhs – ₹1 Crore",
    "₹1 Crore – ₹5 Crores",
    "₹5 Crores – ₹25 Crores",
    "₹25 Crores – ₹100 Crores",
    "₹100 Crores – ₹500 Crores",
    "Above ₹500 Crores",
]

# ---------------- RESTRICTED FIELDS ----------------
RESTRICTED_FIELDS = {
    "admin_approval", "candidate_approval", "category",
    "phone", "profile_id",
}

# ---------------- AIRTABLE FIELD MAPPING ----------------
# Maps internal field keys -> exact Airtable column names (case-sensitive)
AIRTABLE_FIELDS = {
    "phone": "Whatsapp Number",
    "profile_type": "Profile Type",
    "full_name": "Name",
    "dob": "Date of Birth",
    "age": "Age",
    "time_of_birth": "Time of Birth",
    "place_of_birth": "Place of Birth",
    "nakshatra": "Nakshatra",
    "swa_gothram": "SwaGothram",
    "rashi": "Rashi",
    "maternal_gothram": "Maternal Gothram",
    "height": "Height",
    "qualification": "Qualification",
    "profession": "Work",
    "salary_package": "Salary Package",
    "father_name": "Fathers Name",
    "mother_name": "Mothers Name",
    "father_occupation": "Father Occupation",
    "mother_occupation": "Mother Occupation",
    "property_details": "Property",
    "country_of_person": "Person Country",
    "country_of_parents": "Parent Country",
    "candidate_approval": "Candidate Approval",
    "admin_approval": "Admin Approval",
    "category": "Category",
    "created_date": "Created Date",
    "last_update_date": "Last Update Date",
    "person_image": "Person Image",
    "biodata_file": "Biodata File",
}

# Field key -> user-friendly label
FIELD_LABELS = {
    "full_name": "Full Name",
    "dob": "Date of Birth",
    "age": "Age",
    "time_of_birth": "Time of Birth",
    "place_of_birth": "Place of Birth",
    "nakshatra": "Nakshatra",
    "swa_gothram": "Swa Gothram",
    "rashi": "Rashi",
    "maternal_gothram": "Maternal Gothram",
    "height": "Height",
    "qualification": "Education / Qualification",
    "profession": "Profession / Work",
    "salary_package": "Annual Income",
    "father_name": "Father's Name",
    "mother_name": "Mother's Name",
    "father_occupation": "Father's Occupation",
    "mother_occupation": "Mother's Occupation",
    "property_details": "Property",
    "country_of_person": "Your City and Country",
    "country_of_parents": "Parents' City and Country",
}

# Map user-typed text (in update flow) -> internal field key
FIELD_KEYWORD_MAP = {
    "country": "country_of_person",
    "residence": "country_of_person",
    "your country": "country_of_person",
    "parents country": "country_of_parents",
    "parents": "country_of_parents",
    "name": "full_name",
    "full name": "full_name",
    "dob": "dob",
    "date of birth": "dob",
    "birthday": "dob",
    "time": "time_of_birth",
    "birth time": "time_of_birth",
    "time of birth": "time_of_birth",
    "place": "place_of_birth",
    "birth place": "place_of_birth",
    "place of birth": "place_of_birth",
    "height": "height",
    "nakshatra": "nakshatra",
    "birth star": "nakshatra",
    "star": "nakshatra",
    "rashi": "rashi",
    "zodiac": "rashi",
    "swa gothram": "swa_gothram",
    "gothram": "swa_gothram",
    "gotra": "swa_gothram",
    "maternal gothram": "maternal_gothram",
    "maternal": "maternal_gothram",
    "education": "qualification",
    "qualification": "qualification",
    "profession": "profession",
    "job": "profession",
    "work": "profession",
    "salary": "salary_package",
    "income": "salary_package",
    "package": "salary_package",
    "father name": "father_name",
    "father's name": "father_name",
    "mother name": "mother_name",
    "mother's name": "mother_name",
    "father occupation": "father_occupation",
    "father's occupation": "father_occupation",
    "mother occupation": "mother_occupation",
    "mother's occupation": "mother_occupation",
    "property": "property_details",
    "image": "person_image",
    "photo": "person_image",
    "picture": "person_image",
}

# Registration step order - drives the state machine
REGISTRATION_STEPS = [
    "profile_type",
    "country_of_person",
    "country_of_parents",
    "registration_method",
    "full_name",
    "dob",
    "time_of_birth",
    "place_of_birth",
    "height",
    "nakshatra",
    "rashi",
    "swa_gothram",
    "maternal_gothram",
    "qualification",
    "profession",
    "salary_package",
    "father_name",
    "mother_name",
    "father_occupation",
    "mother_occupation",
    "property_details",
    "person_image",
    "review",
    "submit",
]

# OCR extractable fields - Nakshatra/Rashi EXCLUDED by design
OCR_EXTRACTABLE_FIELDS = [
    "full_name",
    "dob",
    "time_of_birth",
    "place_of_birth",
    "height",
    "swa_gothram",
    "maternal_gothram",
    "qualification",
    "profession",
    "salary_package",
    "father_name",
    "mother_name",
    "father_occupation",
    "mother_occupation",
    "property_details",
]